name: run R script

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
      # Checks out repository
      - uses: actions/checkout@v2
      
      # Sets up miniconda and environment
      - uses: conda-incubator/setup-miniconda@v2
        with:
           miniconda-version: "latest"
           activate-environment: epp_project_sven_jacobs
           environment-file: environment.yml
           auto-activate-base: false
      
      - name: run R script  
        run: source("src/functions.R")
	shell: Rscript {0}